name: guardium-estap-{NAME_SUFFIX} # Argo CD application resource name
project: default # Argo CD project
namespace: user1-bgd # Ensures namespace in destination cluster exists. 


# This section contains the values for the helm chart
values: |-
  estap:
    db:
      host: "{DB_HOST}"
      port: {DB_PORT}
      type: "{DB_TYPE}"
    guardium:
      host: "{GUARDIUM_HOST}"
    proxy:
      listen_port: {DB_PORT}
    replicas: 1
    serviceAccountName: default
    fsGroup: 1000690000
    uid: 1000690000
  global:
    imagePullPolicy: IfNotPresent
    dockerRegistryPrefix: "icr.io/guardium-insights"
    tag: "v11.5.3"
    secret: "estap-secret-{NAME_SUFFIX}"
    secretWriterServiceAccountName: "estap-secret-writer-{NAME_SUFFIX}"
